### ISSUE TITLE
MY₿ONK orchestrator to be integrated within MY₿ONK-core 

### ISSUE THREAD

**Issue by we-do-it-lu** [mybonk/mybonk-wiki#30]
MY₿ONK orchestrator is what is used to deploy/orchestrate a [fleet of] MY₿ONK console[s],
MY₿ONK orchestrator is currently a separate Linux machine with a few additional software installed on, including the Nix package manager. 
MY₿ONK orchestrator to be integrated within MY₿ONK-core (meaning run on the MY₿ONK consoles so any MY₿ONK console can act as MY₿ONK orchestrator).

The installation process will be significantly smaller (no need to build a separate Linux to act as MY₿ONK orchestrator).

**Comment by mybonk** [comment]
This is closed.
MY₿ONK orchestrator machine no longer required. Any machine is an orchestrator now using nixos-build selecting the "source" and "target" machines. Also 1 liner installer being worked on but that's another story.
