### ISSUE TITLE
Fix MY₿ONK MVP nixOS configuration

### ISSUE THREAD

**Issue by we-do-it-lu** [mybonk/mybonk-wiki#31]
Fix MY₿ONK MVP nixOS configuration keeping `/docs/INSTALLATION.md` updated accordingly.

**Comment by mybonk** [comment]
Config pushed in GitHub this week

**Comment by we-do-it-lu** [comment]
mybonk-wiki and mybonk-core are now pretty much set and we played with them quite a few.
"MVP" was just that: 

- Making sure that [mybonk-wiki](https://github.com/mybonk/mybonk-wiki/blob/main/README.md) is developed sufficiently for people that are not technical experts but have *some* technical knowledge would find bearable to follow along.
- Making sure that the [mybonk-core](https://github.com/mybonk/mybonk-core), particularly the sub-directory `mybonk-console` is usable in such a way that anyone would really easily be able to deploy MYBONK on remote console by using only a few commands.
- It was not possible to configure the system in such a way that SIGNET would run in parallel with MAINNET, would be a difficult task to accomplish, maybe one day...
