### ISSUE TITLE
feat: Plz share Tmuxinator configuration

### ISSUE THREAD

**Issue by bitbazuka** [mybonk/mybonk-wiki#44]
It would help everyone and would ease checking things out on one another's terminal. 
Would make it easier looking at each other's screen and have a common familiar terminal layout.

**Comment by we-do-it-lu** [comment]
I will share the one I used in the latest demo on some directory on GitHub

**Comment by we-do-it-lu** [comment]
Done. Pushed .tmuxinator_console.yml. 

IMPORTANT: If you don't use tmux/tmuxinator yet explore this baby rabbit hole and play around with it a little bit to avoid pain, it will save you a lot of time.

$ tmuxinator start -p .tmuxinator_console.yml console node="console_jay"

Notes: 
- Adjust the parameter `-p` accordingly if you are not running the command from the project's root.
- You must pass the extra custom parameter `node` that must be either an IP address or a hostname (mapped in hosts file).
