### ISSUE TITLE
update link to configuration.nix section

### ISSUE THREAD

**Issue by northben** [mybonk/mybonk-wiki#48]
https://github.com/northben/mybonk-core/blob/main/docs/Procedure.md#configuration.nix

The anchor `#configuration.nix` on this page doesn't seem to exist

> configuration.nix: Explained in a [previous section](https://github.com/mybonk/mybonk-wiki/issues/new#configuration.nix).

**Comment by we-do-it-lu** [comment]
Reworded
Pushed 0f4cec5
Closed
